companies:
- name: Watershed
- name: Redwood Materials
- name: QuantumScape
- name: Form Energy
- name: Fervo Energy
- name: Antora Energy
- name: Electric Hydrogen
- name: Base Power Company
- name: Sila Nanotechnologies
- name: Natron Energy
- name: WeaveGrid
- name: Camus Energy
- name: Overstory
- name: Persefoni
- name: Crux Climate
- name: Common Energy
- name: Terraform Industries
- name: Mill Industries
- name: Our Next Energy
- name: Aurora Solar
- name: Arcadia
- name: Sunrun
- name: ChargePoint
- name: Span
- name: Heirloom
- name: Climeworks
- name: Chestnut Carbon
- name: Charm Industrial
- name: Rondo Energy
- name: Lilac Solutions
- name: Pachama
- name: CarbonCure Technologies
- name: Carbon Engineering
- name: Carbon Lighthouse
- name: Carbon Upcycling Technologies
- name: Raptor Maps
- name: Terabase Energy
- name: Active Surfaces
- name: Kitekraft
- name: BlocPower
- name: Bidgely
- name: Amperon
- name: AMPLY Power
- name: AMP Robotics
- name: AmpUp
- name: Aquabyte
- name: Arbor Energy
- name: Arc Boats
- name: Arka Energy
- name: Ark Biotech
- name: Artyc
- name: Avalanche Energy
- name: Axiom Cloud
- name: Azavea
- name: Banyan Infrastructure
- name: BasiGo
- name: Bellwether Coffee
- name: Benson Hill
- name: BioLite Energy
- name: Blue Planet Energy Systems
- name: Boston Metal
- name: Boundary Layer Technologies
- name: Breathe Battery Technologies
- name: Cambrian Innovation
- name: Carbon America
- name: CarbonChain
- name: Carbon13
- name: Carbonwave
- name: CATALOG
- name: Ceres Imaging
- name: Cervest
- name: ChargerHelp!
- name: Chargetrip
- name: Chooose
- name: Citrine Informatics
- name: Clairity Technologies
- name: CleanFiber
- name: Clearflame Engine Technologies
- name: ClearTrace
- name: ClimateAi
- name: Aeroseal
- name: Ampaire
- name: Alloy Enterprises
- name: Allume Energy
- name: Altus Thermal
- name: Amber Kinetics
- name: Ambri
- name: Advanced Ionics
- name: Aepnus Technology
- name: Aquaria
- name: Arable
- name: Arca
- name: ArcTern Ventures
- name: Rise Reforming
- name: OctaPulse
- name: Rimba
- name: Plume
- name: Silurian
- name: NetworkOcean
- name: Sorcerer
- name: HyLight
- name: Nira Energy
- name: Voltic
- name: ALT TEX
- name: Wand Solar
- name: BuyPower
- name: Birch Biosciences
- name: Paces
- name: Posh
- name: Carbon Crusher
- name: AirMyne
- name: Alga Biosciences
- name: Phase Biolabs
- name: Seabound
- name: Impossible Metals
- name: Phykos
- name: Ferveret
- name: Living Carbon
- name: Enerjazz
- name: Carbonfact
- name: Abatable
- name: Remora
- name: Minimum
- name: StratumAI
- name: EARTH AI
- name: Maple Materials
- name: Valo
- name: Wren
- name: Aerones
- name: Airthium
- name: Advano
- name: Releaf Earth
- name: SunFarmer
- name: GBatteries
- name: PowerX
- name: Glow Energy
- name: Pina Earth
- name: Orbillion Bio
- name: Valor Water Analytics
- name: Helix Carbon
- name: Carbion
- name: LNK Energies
- name: Bright
- name: 120Water
- name: 2X Global
- name: Activate Global
- name: Additional Ventures
- name: ADL Ventures
- name: Antenna Group
- name: Arloid Automation Science & Technology Consultancy
- name: Asia Investor Group on Climate Change
- name: Asset Resolution
- name: Atlantic Council
- name: Audette
- name: Balance Eco Ltd
- name: BART
- name: battgenie.life
- name: Beta Bugs
- name: Biomimicry 3.8
- name: BlueGreen Alliance
- name: Blue Ocean Barns
- name: Bodhi
- name: Boston Materials
- name: Bridgemans Services Group
- name: California Climate Action Corps
- name: Callirius AG
- name: Cambrian Innovation Inc
- name: Capex
- name: Carbon Limiting Technologies
- name: CarbonPlan
- name: Carbyon
- name: Center for International Environmental Law
- name: Centre for Research on Energy and Clean Air
- name: Chewie Labs
- name: cirplus GmbH
- name: City of Bainbridge Island
- name: Clean Energy Ventures
- name: ClearPath
- name: ClearVUE.Business
- name: ClimaFi
- name: Climate Action Systems
- name: Climate Advisers
- name: 2S Water Incorporated
- name: '44.01'
- name: 75F
- name: Aclarity
- name: Aclima, Inc.
- name: Actionfigure
- name: Activate
- name: Advanced Energy United
- name: Aepnus Technologies
- name: AGERpoint
- name: Agreena
- name: Aigen
- name: Aikido Technologies
- name: Air Company
- name: AirLoom Energy
- name: Albedo
- name: alcemy
- name: Allium Engineering
- name: Alpine Bio
- name: Aluminio
- name: Amini
- name: Ammobia
- name: Amogy
- name: AMP
- name: Andes
- name: ANNEA.ai GmbH
- name: Anthro
- name: Aperia Technologies
- name: Applied Intuition
- name: AptDeco
- name: Aqua Membranes
- name: Aquatic Labs
- name: Arbor
- name: Arc
- name: Arch
- name: Arculus Solutions
- name: Arnergy
- name: Array Labs
- name: Ascribe Bioscience
- name: Aspiring Materials
- name: Astro Mechanica
- name: Atlas Materials
- name: Autogrid
- name: Avalo
- name: Avnos, Inc.
- name: Axle Mobility
- name: Azolla Ventures
- name: Banyu Carbon
- name: Baseload Capital
- name: Beagle Services
- name: Bedrock Energy
- name: Beekeeper
- name: Beijing Climate Policy Initiative
- name: BETA Technologies
- name: Better Packaging
- name: Better Place Forests
- name: Better Ventures
- name: BHI Energy
- name: Biki
- name: BlackCurrant
- name: Bloom Biorenewables Ltd
- name: Blue Current
- name: Blue Frontier
- name: Blue Lake Packaging
- name: Blue Planet Energy Systems, LLC
- name: Blue World Technologies
- name: Blumen
- name: Blyncsy
- name: Bolt.Earth
- name: Boundless Impact Research & Analytics
- name: Branch Energy
- name: Breathe
- name: BRIGHT
- name: Bright Harbor
- name: Brightband
- name: Brightside
- name: Brimstone
- name: Brooklyn SolarWorks
- name: BurnBot
- name: C.Scale
- name: C16 Biosciences
- name: Cache Energy
- name: Cala Systems
- name: Calcarea
- name: Calectra
- name: Calion Technologies
- name: Cambio
- name: Cambium
- name: CamoAg
- name: Capella Space
- name: Capture6
- name: Carbon Collective
- name: Carbon Reform
- name: Carbon180
- name: CarbonBuilt
- name: CarbonCapture
- name: Carbonfuture
- name: Carboniferous
- name: CarbonRun
- name: Cascade Biocatalysts
- name: Cascade Climate
- name: Celerity Consulting Group
- name: Celluol
- name: Cemvision
- name: CERT Systems
- name: Charge Robotics
- name: Chef Ann Foundation
- name: Chement
- name: ChemFinity Technologies
- name: CIMCON Lighting
- name: Circ
- name: Circle Seafoods
- name: Cirplus
- name: CivilGrid
- name: Clean Crop Technologies
- name: Clear Skies Hydrogen
- name: Clearloop
- name: Climate Farmers
- name: ClimateAI
- name: ClimateCrop
- name: CO280 Solutions
- name: Coalition for Green Capital
- name: Coastal Carbon
- name: Cobalt
- name: Coconut Bliss
- name: Cocoon
- name: Commons
- name: Commonwealth Fusion Systems
- name: Community Energy Labs
- name: Conduit Tech
- name: ConnectDER
- name: Consentio
- name: Coperniq
- name: Copper
- name: Courial
- name: Cove
- name: CowBell Labs
- name: CREW Carbon
- name: Crowd Cow
- name: Crusoe
- name: Crux
- name: Cubicpv Inc.
- name: Cypris Materials
- name: Dance
- name: Dandelion Energy
- name: Daupler
- name: David Energy
- name: dcbel
- name: Deep Sky
- name: Dendra Systems
- name: Diamond Foundry
- name: Dig Energy
- name: DigitalPaani
- name: Dimensional Energy
- name: Dioxycle
- name: Dispatch Goods
- name: Dollaride
- name: Down Ballot Climate Partners
- name: DroneDeploy
- name: Earthmover
- name: EarthSense, Inc.
- name: Earthshot Labs
- name: Eat Real Certified
- name: Ebb Carbon
- name: Eclipse Foods
- name: ecobee
- name: Ecocem Ireland
- name: EcoSafi
- name: ecoworks
- name: Edacious
- name: Eion
- name: Electric Era Technologies
- name: ElectricFish
- name: Electroflow
- name: Element Energy
- name: Elemental Excelerator
- name: Elephant Energy
- name: Eli
- name: Energetic Insurance
- name: Energize Capital
- name: Energy Dome
- name: Energy Web Foundation
- name: EnergyHub
- name: Enode
- name: Ento Labs
- name: Entocycle
- name: enVerid Systems
- name: Enzymit
- name: Epoch Biodesign
- name: Equatic
- name: Equilibrium Energy
- name: eSmart Systems
- name: Espiku
- name: ESS
- name: Ethic
- name: Euclid Power
- name: Ev.energy
- name: Everrati
- name: EVOLOH
- name: Evrnu
- name: Ezra Climate
- name: Farm Holdings
- name: "Farm Link Hawai\u2018i"
- name: FarmRaise
- name: Felt
- name: Ferrum Technologies
- name: First Street Foundation
- name: FirstFuel Software
- name: Flair
- name: Fleet
- name: Fleet Robotics
- name: Fleetzero
- name: FLO
- name: Floodbase
- name: FloodMapp
- name: FlyWire
- name: FoodMaven
- name: For Days
- name: Forerunner
- name: Formo
- name: Fortify
- name: Forum Mobility
- name: Fourth Power
- name: Fox Robotics
- name: FRACTAL
- name: Fram Energy
- name: FREDsense
- name: Frost Methane
- name: Full Cycle Bioplastics
- name: Full Harvest
- name: Funga
- name: Fuse Energy
- name: FutureProof Technologies
- name: Fyto
- name: Gallox Semiconductor
- name: GALY
- name: Geli
- name: Gencores
- name: General Biological
- name: Genomines
- name: Get Lit
- name: Get Weatherized, Inc.
- name: getamber
- name: Glacier
- name: Go Electric
- name: GoodLynx
- name: Goodr
- name: Gradient
- name: GRAIN Ecosystem
- name: Graphyte
- name: Gravity Climate
- name: Greenlight America
- name: Greenlight Biosciences
- name: Greenly
- name: Gridware
- name: GridX
- name: Grover
- name: Guidewheel
- name: H2Pro
- name: Halter
- name: Hawaii'i 'Ulu Cooperative
- name: Heart Aerospace
- name: Heartee Foods
- name: Heaten
- name: Helio Home
- name: Heliogen
- name: HerdDogg
- name: Hertha Metals
- name: Hgen
- name: HILOS
- name: Hippo Harvest
- name: HIVED
- name: Hohonu
- name: Holocene
- name: Holy Grail
- name: HomeBoost
- name: Hoofprint Biome
- name: HOPE Hydration
- name: Hopthru
- name: HowGood
- name: Hoxton Farms
- name: HST
- name: Hyperframe
- name: HyperHeat
- name: Impossible Foods
- name: Industrious Labs
- name: Infinitum
- name: Infinium
- name: Infravision
- name: Innowatts
- name: InRange
- name: Insight M
- name: Instagrid
- name: Intensivate
- name: INVERSA Leathers
- name: Ion Solar
- name: Irrigreen
- name: Isometric
- name: it's electric
- name: Jaro Fleet Technologies
- name: Jupiter Intelligence
- name: Kando
- name: Kaya Pay
- name: Kelvin
- name: Kettle
- name: Kevala
- name: Kindred Motorworks
- name: Kinetic Automation
- name: Kinfield
- name: King Energy
- name: KoBold Metals
- name: Kodama Systems
- name: Koloma
- name: Kopperfield
- name: Kula Bio
- name: kWh Analytics
- name: LAIIER
- name: LandTrust
- name: Lastwall Networks, Inc.
- name: Latitude Media
- name: Leaf Agriculture
- name: Leap
- name: Lemon Energy
- name: LevelTen Energy
- name: Li-Cycle
- name: Lightship
- name: Lime
- name: Limelight Steel
- name: Liminal
- name: Linear Labs
- name: Liquium
- name: Lithios
- name: Lithos Carbon
- name: Loamist
- name: Local Line
- name: Lumen Energy
- name: Lun
- name: LuxWall
- name: Machina Labs
- name: Macro Oceans
- name: MacroCycle
- name: Mad capital
- name: Made of Air
- name: Magrathea
- name: Malta
- name: Mangrove Lithium
- name: Mangrove Systems
- name: Mantel
- name: Manus Bio
- name: Marathon Fusion
- name: Marble
- name: Mars Materials
- name: Material Evolution
- name: Matician
- name: Matter.
- name: Maui Nui Venison
- name: Measurabl
- name: Meati Foods
- name: Meridian Clean Energy
- name: Microvi Biotechnologies
- name: Mill
- name: MineSense Technologies
- name: Mission Barns
- name: Mission Zero
- name: Mittilabs
- name: Modulous
- name: MOLG
- name: Molten Industries
- name: MOMBAK
- name: Moment Energy
- name: Monarch Tractor
- name: Monta
- name: Mootral
- name: Mori
- name: Mosa Meat
- name: Mosaic
- name: Moxion Power
- name: Muon Space
- name: Muon Vision
- name: Musa Tecnologia LTDA
- name: MycoWorks
- name: Mythos AI
- name: Natel Energy
- name: "Nature\u2019s Fynd"
- name: Nav
- name: Navier
- name: NCX
- name: Near Space Labs
- name: Neara
- name: NEER
- name: Neutral
- name: Neutreeno
- name: Nitricity
- name: NitroVolt
- name: NLine Energy
- name: Nnergix
- name: Nori
- name: Normative.io
- name: Novalith Technologies
- name: Novel Farms
- name: Novi
- name: Novoloop
- name: Noya
- name: Nth Cycle
- name: Nuventura
- name: Odyssey
- name: Office of Clean Energy Demonstrations
- name: Ohmconnect
- name: Oklo
- name: Olokun Minerals
- name: Omeat
- name: Omnidian
- name: OnePointOne
- name: Onsemble
- name: Onvector
- name: Oonee
- name: Optera
- name: OptimoRoute Inc.
- name: Opus One Solutions
- name: Orange Charger
- name: Orbio Earth
- name: Origen
- name: oroeco
- name: Ostrom
- name: Othersphere
- name: Overview Energy
- name: Ovipost
- name: OzoneBio
- name: Pacific Fusion
- name: Packfleet
- name: Palmetto
- name: Pano
- name: Panthalassa
- name: Pantheon Regeneration
- name: Parallel Systems
- name: Pasture Biosciences
- name: PastureMap
- name: Patch
- name: Pathways
- name: Pearl Street Technologies
- name: Pendulum Systems
- name: PermitFlow
- name: Petra
- name: Phase Genomics
- name: Phoenix Tailings
- name: Phycobloom
- name: Phytoform Labs
- name: Piclo
- name: Pico MES
- name: Pioneer Power Solutions
- name: Pioneer Transformers
- name: Pivot Bio
- name: Planet
- name: Planet A Foods
- name: Planet FWD
- name: Plant Prefab
- name: Plenty
- name: Plotlogic
- name: Plug
- name: polySpectra
- name: Pono Home
- name: Populus
- name: Power Factors
- name: Powerline
- name: Powin
- name: Presto
- name: Project Canary
- name: Prolific Machines
- name: Propagate Ventures
- name: Prospect Growth
- name: Proterra
- name: Provision Analytics
- name: PulSenics
- name: Pulsora
- name: Pyka
- name: Quaise Energy
- name: Queens Carbon
- name: Quidnet Energy
- name: Quilt
- name: QuitCarbon
- name: Radiant
- name: RailVision
- name: Rainmaker
- name: Rally
- name: Rarefied Technologies
- name: RatedPower
- name: Re-Nuble
- name: Reach
- name: Reactive Technologies
- name: Reath
- name: Rebound Technologies
- name: Recharged
- name: Recurrent
- name: Recurrent Technologies, Inc.
- name: Redoxblox
- name: ReFED
- name: Refiberd
- name: Regrow
- name: Relativity Space
- name: Reliable Robotics
- name: Remix
- name: Renaissance Fusion
- name: Rendered.ai
- name: Renew Financial
- name: RenewCO2
- name: Reunion
- name: Rewind
- name: Rheaply
- name: Ride Report
- name: RIFT
- name: Ripple Foods
- name: River
- name: Rivian
- name: Robigo
- name: Roble Eco
- name: Rosy Soil
- name: RUBI LABORATORIES
- name: Rumin8
- name: Run on Climate
- name: Runwise
- name: Sabanto
- name: Safehub
- name: Safi
- name: SailPlan
- name: Salient Predictions
- name: Salt
- name: Scalvy
- name: Scoot Science
- name: Scope3
- name: Scythe Robotics
- name: Senken
- name: Sense
- name: Sentient Energy
- name: SewerAI
- name: Shelf Engine
- name: Shift EV
- name: Shifted Energy
- name: Shower Stream
- name: SHYFT Power Solutions
- name: Sibros
- name: Sierra Energy
- name: Sightline Climate
- name: Signol
- name: Silicate
- name: Silo
- name: SilverLining
- name: Singularity Energy
- name: Sinkco Labs
- name: SirenOpt
- name: Sitetracker
- name: SiTration
- name: Skyven Technologies
- name: Smallhold
- name: Smartcar
- name: SmartRent
- name: Sofar Ocean
- name: Soil Carbon Co.
- name: Soiltech Wireless
- name: SolarAPP Foundation
- name: SolarSquare Energy
- name: Solcoa Technologies
- name: Solidia Technologies
- name: Solidspac3
- name: Solstice
- name: Solugen
- name: Sortera Alloys
- name: SOURCE
- name: Sourcemap
- name: SPAN
- name: Spark (YC W24)
- name: SparkCharge
- name: SparkMeter
- name: Specifx Data
- name: Spoor
- name: Spout Water
- name: Stable
- name: Stand
- name: Standard Potential
- name: Stem
- name: Step Function
- name: Still Bright
- name: STOKE Space Technologies
- name: Stripe, Frontier
- name: Subeca
- name: Sublime Systems
- name: Sunthetics
- name: Supercircle
- name: Supercritical
- name: Superorganism
- name: Sustaera
- name: Sustain.Life
- name: Sustainable Chemicals
- name: Sustainment
- name: SWARM Engineering
- name: Sway
- name: Sweep
- name: Swift Solar
- name: SwiftComply
- name: Swiftly
- name: Sylvatex
- name: Sylvera
- name: Synop
- name: Takachar
- name: Tandem PV
- name: Tangible
- name: TeamSolve
- name: Technosylva
- name: Telesense
- name: Telo Trucks
- name: Tender Food
- name: Terra CO2 Technologies
- name: Terra.do
- name: Terradot
- name: Terraformation
- name: Terrafuse
- name: Terraline
- name: Terralytiq
- name: Terviva
- name: Tetra
- name: Thalo Labs
- name: The Climate Choice
- name: The Demex Group
- name: The Eastern Specialty Company
- name: The Routing Company
- name: Thea Energy
- name: Thousand Fell
- name: Thrilling
- name: Thrive Lot
- name: Tidal Metals
- name: Toggle Robotics
- name: Topanga.io
- name: Toucan Protocol
- name: Trace Genomics
- name: TradeLanes
- name: Trailhead Capital
- name: Transaera
- name: Transcend
- name: Transmutex
- name: TreeCard
- name: Treehouse
- name: Trove
- name: TS Conductor
- name: Turntide Technologies
- name: TWAICE
- name: Twelve
- name: Tyba
- name: Ulysses
- name: Uncommon
- name: Understory
- name: UNDO
- name: Unemit
- name: UNLESS Collective
- name: unspun
- name: Uplight
- name: Urban Machine
- name: Urbint
- name: UtilityAPI
- name: VALIS
- name: Vantem Global
- name: Vatn Systems
- name: Vaulted Deep
- name: Vecna Robotics
- name: Vector
- name: VEIR
- name: Vence
- name: Verdigris Technologies
- name: Verdox
- name: Verne
- name: Verse Inc.
- name: Vesta
- name: VIA
- name: Via
- name: Vibrant Planet
- name: Viking Cold Solutions
- name: Visolis
- name: Volta Charging
- name: Voltus
- name: Waterplan
- name: WATS
- name: WattBuy
- name: Weave Grid
- name: WEEE Centre
- name: WhereIsMyTransport
- name: White Leaf Provisions
- name: Windfall Bio
- name: Work on Climate
- name: Worldly
- name: Wright Electric
- name: Wunder
- name: XFuel
- name: Xilinat
- name: XL Fleet
- name: Xos Trucks
- name: Xtelligent
- name: XWING
- name: Yard Stick PBC
- name: Zanskar
- name: Zap Energy
- name: Zero Homes
- name: ZeroAvia
- name: Zhero
- name: ziptility
- name: Zitara
- name: zolar
- name: ZwitterCo
